from ..bbdd.db_connector import DBConnector
from ..bbdd.connectors import MongoConnector
from datetime import date, timedelta, datetime
import requests
import json
from typing import Dict, List

class DataCollector:
    """
    This class is responsible for obtaining the data and storing it in a database.
    MongoDB is the chosen database. 
    """

    DB_INFO_PATH = 'bbdd/db_info.ini'
    ENDPOINT_URL = 'https://demanda.ree.es/WSvisionaMovilesPeninsulaRest/resources/demandaGeneracionPeninsula?fecha='
    CO2_EMISSIONS_FACTOR = {
        'aut': 0.27,
        'car': 0.95,
        'cc': 0.37,
        'cogenResto': 0.27,
        'gf': 0.7,
        'termRenov': 0.27
    }

    def __init__(self) -> None:
        self._connection = self._create_connection()

    def _create_connection(self) -> object:
        """
        Creates a connection with a database

        Returns
        -------
        connection : object
            Object which handles the connection to the database
        """
        # Initializes a DBConnector with a MongoConnector
        db_connector = DBConnector(MongoConnector())

        return db_connector.connect_to_db(self.DB_INFO_PATH)

    def retrieve_last_day(self) -> None:
        """
        Retrieves data from the previous day
        """
        # Generates the endpoint from which obtain the data
        previous_day_str = self._generate_previous_day_date()
        endpoint = self.ENDPOINT_URL + previous_day_str
        # Retrieves the data from the endpoint
        energy_data = self._retrieve_energy_data(endpoint)
        # Generates the emissions data from the energy_data
        emissions = self._generate_emissions(energy_data)

        # Creates the document containing the data and inserts it into the database
        document = self._generate_document(emissions, previous_day_str)
        self._insert_document(document)

    def _generate_previous_day_date(self) -> str:
        """
        Generates the endpoint for the previous day data

        Returns
        -------
        endpoint : str
            Endpoint to retrieve the previous day data
        """
        today = date.today()
        previous_day = today - timedelta(days=1)
        previous_day_str = previous_day.strftime('%Y-%m-%d')

        return previous_day_str

    def _retrieve_energy_data(self, url: str) -> List[Dict]:
        """
        Retrieve all the text from a given url

        Parameters
        ----------
        url : str
            String containing the endpoint url

        Returns
        -------
        json_data : list 
            List containing a dictionary for each observation
        """
        # Gets the raw data in json format
        page = requests.get(url)
        data = page.text

        # Cleans the data to leave only the json part
        data = data.replace('null({"valoresHorariosGeneracion":', '')
        data = data.replace('});', '')
        # Decodes the json
        json_data = json.loads(data)

        return json_data

    def _generate_emissions(self, json_data: List[Dict]) -> dict:
        """
        Generates a new dictionary which contains the emissions for each timestamp.
        The dictionary has the following format e.g :
        {
            '2020-08-27 21:00': 1000,
            ...
        }
        """
        emissions = {}

        for observation in json_data:
            timestamp = observation['ts']
            emissions[timestamp] = self._compute_emissions(observation)

        return emissions

    def _compute_emissions(self, observation: dict) -> float:
        """
        Compute the emissions generated in an observation

        Parameters
        ----------
        observation : dict
            Dictionary representing an observation in time. It includes
            the timestamp along with the energy generated by each type of energy

        Returns
        -------
        total_emissions : float
            Total sum of emissions for the observation
        """
        # List of energies which generate CO2 emissions
        polluting_energies = ['aut', 'car', 'cc', 'cogenResto', 'gf', 'termRenov']

        # List with the emissions for each energy
        emissions = [observation[energy] * self.CO2_EMISSIONS_FACTOR[energy] for energy in polluting_energies]
        # Get an unique emissions value
        total_emissions = sum(emissions)

        return total_emissions

    def _generate_document(self, emissions: dict, previous_day_str: str) -> dict:
        """
        Generates a document to be inserted into the database

        Parameters
        ----------
        emissions : dict
            Dictionary containing the emissions related data

        previous_day_date_str : str
            Previous day date as a string

        Returns
        -------
        document : dict
            Dictionary containing the document information
        """
        # Generates a datetime object from a date string
        previous_day = datetime.strptime(previous_day_str, '%Y-%m-%d')

        document = {
            'date': previous_day,
            'emissions': emissions
        }

        return document

    def _insert_document(self, document: dict) -> None:
        """
        Inserts a new record in the database

        Parameters
        ----------
        data : dict
            Dictionary containing the data to be stored
        """
        # Gets the collection which stores raw data
        collection = self._connection.raw_collector

        collection.insert_one(document)